/**
 * 多语言支持文件
 * Multilingual support file
 */

const translations = {
    // 中文翻译
    'zh': {
        // 导航栏
        'nav_home': '首页',
        'nav_competitions': '竞赛信息',
        'nav_teammates': '寻找队友',
        'nav_profile': '个人资料',
        'login': '登录',
        'register': '注册',
        
        // 通知
        'notifications': '通知',
        'mark_all_read': '全部标为已读',
        'no_notifications': '没有新通知',
        'see_all_notifications': '查看所有通知',
        
        // 首页
        'hero_title': '寻找您的国际竞赛最佳队友',
        'hero_subtitle': '连接全球学生，组建完美团队，赢得国际竞赛',
        'get_started': '开始使用',
        'learn_more': '了解更多',
        'features_title': '为什么选择 teamify？',
        'feature1_title': '全球人才库',
        'feature1_desc': '接触来自世界各地的优秀学生，找到完美匹配的队友',
        'feature2_title': '技能匹配',
        'feature2_desc': '基于技能、经验和兴趣的智能匹配系统',
        'feature3_title': '竞赛资源',
        'feature3_desc': '获取最新竞赛信息、截止日期和参赛要求',
        'popular_competitions': '热门竞赛',
        'view_all': '查看全部',
        'days_left': '剩余天数',
        'testimonials_title': '用户反馈',
        'cta_title': '准备好开始您的竞赛之旅了吗？',
        'cta_subtitle': '今天就注册，找到您的理想队友',
        'cta_button': '立即注册',
        
        // 页脚
        'quick_links': '快速链接',
        'about_us': '关于我们',
        'contact_us': '联系我们',
        'privacy_policy': '隐私政策',
        'terms_of_service': '使用条款',
        'follow_us': '关注我们',
        'copyright': '版权所有',
        
        // 聊天
        'chats': '聊天',
        'contacts': '联系人',
        'search': '搜索',
        'new_chat': '新建聊天',
        'online': '在线',
        'offline': '离线',
        'type_message': '输入消息...',
        'send': '发送',
        'chat_info': '聊天信息',
        'media': '媒体',
        'files': '文件',
        'links': '链接',
        'create_group': '创建群组',
        'add_members': '添加成员',
        'group_name': '群组名称',
        'create': '创建',
        'cancel': '取消',
        'typing': '正在输入...',
        
        // 登录/注册
        'welcome_back': '欢迎回来',
        'login_subtitle': '登录您的账号，继续寻找最佳队友',
        'email': '电子邮箱',
        'password': '密码',
        'remember_me': '记住我',
        'forgot_password': '忘记密码？',
        'no_account': '还没有账号？',
        'create_account': '创建账号',
        'join_community': '加入全球最大的国际学生竞赛社区',
        'full_name': '全名',
        'confirm_password': '确认密码',
        'agree_terms': '我同意使用条款和隐私政策',
        'already_account': '已有账号？',
        
        // 竞赛页面
        'competitions_title': '探索国际竞赛',
        'competitions_subtitle': '发现适合您的最新全球竞赛机会',
        'filter_by': '筛选',
        'all_categories': '所有类别',
        'deadline': '截止日期',
        'team_size': '团队规模',
        'difficulty': '难度',
        'apply_filters': '应用筛选',
        'reset_filters': '重置',
        'competition_details': '竞赛详情',
        'organizer': '主办方',
        'category': '类别',
        'prize': '奖金',
        'requirements': '要求',
        'description': '描述',
        'register_now': '立即报名',
        'find_teammates': '寻找队友',
        
        // 寻找队友页面
        'find_teammates_title': '寻找队友',
        'find_teammates_subtitle': '浏览潜在队友并建立联系',
        'filter_teammates': '筛选队友',
        'skills': '技能',
        'experience': '经验',
        'location': '位置',
        'availability': '可用性',
        'search_teammates': '搜索队友',
        'connect': '连接',
        'message': '发送消息',
        'view_profile': '查看资料',
        
        // 个人资料页面
        'my_profile': '我的资料',
        'edit_profile': '编辑资料',
        'basic_info': '基本信息',
        'university': '大学',
        'major': '专业',
        'bio': '个人简介',
        'my_skills': '我的技能',
        'add_skill': '添加技能',
        'my_competitions': '我的竞赛',
        'past_competitions': '过往竞赛',
        'achievements': '成就',
        'add_achievement': '添加成就',
        'save_changes': '保存更改',
        'discard_changes': '放弃更改'
    },
    
    // 英文翻译
    'en': {
        // Navigation
        'nav_home': 'Home',
        'nav_competitions': 'Competitions',
        'nav_teammates': 'Find Teammates',
        'nav_profile': 'Profile',
        'login': 'Login',
        'register': 'Register',
        
        // Notifications
        'notifications': 'Notifications',
        'mark_all_read': 'Mark all as read',
        'no_notifications': 'No new notifications',
        'see_all_notifications': 'See all notifications',
        
        // Home page
        'hero_title': 'Find Your Perfect International Competition Teammates',
        'hero_subtitle': 'Connect with students globally, build the perfect team, and win international competitions',
        'get_started': 'Get Started',
        'learn_more': 'Learn More',
        'features_title': 'Why Choose teamify?',
        'feature1_title': 'Global Talent Pool',
        'feature1_desc': 'Access exceptional students from around the world to find your perfect match',
        'feature2_title': 'Skill Matching',
        'feature2_desc': 'Smart matching system based on skills, experience, and interests',
        'feature3_title': 'Competition Resources',
        'feature3_desc': 'Get the latest competition information, deadlines, and requirements',
        'popular_competitions': 'Popular Competitions',
        'view_all': 'View All',
        'days_left': 'days left',
        'testimonials_title': 'What Our Users Say',
        'cta_title': 'Ready to Start Your Competition Journey?',
        'cta_subtitle': 'Sign up today and find your ideal teammates',
        'cta_button': 'Register Now',
        
        // Footer
        'quick_links': 'Quick Links',
        'about_us': 'About Us',
        'contact_us': 'Contact Us',
        'privacy_policy': 'Privacy Policy',
        'terms_of_service': 'Terms of Service',
        'follow_us': 'Follow Us',
        'copyright': 'All Rights Reserved',
        
        // Chat
        'chats': 'Chats',
        'contacts': 'Contacts',
        'search': 'Search',
        'new_chat': 'New Chat',
        'online': 'Online',
        'offline': 'Offline',
        'type_message': 'Type a message...',
        'send': 'Send',
        'chat_info': 'Chat Info',
        'media': 'Media',
        'files': 'Files',
        'links': 'Links',
        'create_group': 'Create Group',
        'add_members': 'Add Members',
        'group_name': 'Group Name',
        'create': 'Create',
        'cancel': 'Cancel',
        'typing': 'typing...',
        
        // Login/Register
        'welcome_back': 'Welcome Back',
        'login_subtitle': 'Login to your account to continue finding the best teammates',
        'email': 'Email',
        'password': 'Password',
        'remember_me': 'Remember me',
        'forgot_password': 'Forgot password?',
        'no_account': 'Don\'t have an account?',
        'create_account': 'Create Account',
        'join_community': 'Join the world\'s largest international student competition community',
        'full_name': 'Full Name',
        'confirm_password': 'Confirm Password',
        'agree_terms': 'I agree to the Terms of Service and Privacy Policy',
        'already_account': 'Already have an account?',
        
        // Competitions page
        'competitions_title': 'Explore International Competitions',
        'competitions_subtitle': 'Discover the latest global competition opportunities for you',
        'filter_by': 'Filter by',
        'all_categories': 'All Categories',
        'deadline': 'Deadline',
        'team_size': 'Team Size',
        'difficulty': 'Difficulty',
        'apply_filters': 'Apply Filters',
        'reset_filters': 'Reset',
        'competition_details': 'Competition Details',
        'organizer': 'Organizer',
        'category': 'Category',
        'prize': 'Prize',
        'requirements': 'Requirements',
        'description': 'Description',
        'register_now': 'Register Now',
        'find_teammates': 'Find Teammates',
        
        // Find Teammates page
        'find_teammates_title': 'Find Teammates',
        'find_teammates_subtitle': 'Browse potential teammates and make connections',
        'filter_teammates': 'Filter Teammates',
        'skills': 'Skills',
        'experience': 'Experience',
        'location': 'Location',
        'availability': 'Availability',
        'search_teammates': 'Search Teammates',
        'connect': 'Connect',
        'message': 'Message',
        'view_profile': 'View Profile',
        
        // Profile page
        'my_profile': 'My Profile',
        'edit_profile': 'Edit Profile',
        'basic_info': 'Basic Information',
        'university': 'University',
        'major': 'Major',
        'bio': 'Bio',
        'my_skills': 'My Skills',
        'add_skill': 'Add Skill',
        'my_competitions': 'My Competitions',
        'past_competitions': 'Past Competitions',
        'achievements': 'Achievements',
        'add_achievement': 'Add Achievement',
        'save_changes': 'Save Changes',
        'discard_changes': 'Discard Changes'
    },
    
    // 德语翻译
    'de': {
        // Navigation
        'nav_home': 'Startseite',
        'nav_competitions': 'Wettbewerbe',
        'nav_teammates': 'Teamkollegen finden',
        'nav_profile': 'Profil',
        'login': 'Anmelden',
        'register': 'Registrieren',
        
        // Notifications
        'notifications': 'Benachrichtigungen',
        'mark_all_read': 'Alle als gelesen markieren',
        'no_notifications': 'Keine neuen Benachrichtigungen',
        'see_all_notifications': 'Alle Benachrichtigungen anzeigen',
        
        // Home page
        'hero_title': 'Finden Sie Ihre perfekten Teamkollegen für internationale Wettbewerbe',
        'hero_subtitle': 'Vernetzen Sie sich mit Studenten weltweit, bauen Sie das perfekte Team auf und gewinnen Sie internationale Wettbewerbe',
        'get_started': 'Loslegen',
        'learn_more': 'Mehr erfahren',
        'features_title': 'Warum teamify wählen?',
        'feature1_title': 'Globaler Talentpool',
        'feature1_desc': 'Zugang zu außergewöhnlichen Studenten aus der ganzen Welt, um Ihren perfekten Partner zu finden',
        'feature2_title': 'Kompetenzabgleich',
        'feature2_desc': 'Intelligentes Matching-System basierend auf Fähigkeiten, Erfahrung und Interessen',
        'feature3_title': 'Wettbewerbsressourcen',
        'feature3_desc': 'Erhalten Sie die neuesten Wettbewerbsinformationen, Fristen und Anforderungen',
        'popular_competitions': 'Beliebte Wettbewerbe',
        'view_all': 'Alle anzeigen',
        'days_left': 'Tage übrig',
        'testimonials_title': 'Was unsere Benutzer sagen',
        'cta_title': 'Bereit, Ihre Wettbewerbsreise zu beginnen?',
        'cta_subtitle': 'Melden Sie sich noch heute an und finden Sie Ihre idealen Teamkollegen',
        'cta_button': 'Jetzt registrieren',
        
        // Footer
        'quick_links': 'Schnelllinks',
        'about_us': 'Über uns',
        'contact_us': 'Kontakt',
        'privacy_policy': 'Datenschutzrichtlinie',
        'terms_of_service': 'Nutzungsbedingungen',
        'follow_us': 'Folgen Sie uns',
        'copyright': 'Alle Rechte vorbehalten',
        
        // Chat
        'chats': 'Chats',
        'contacts': 'Kontakte',
        'search': 'Suchen',
        'new_chat': 'Neuer Chat',
        'online': 'Online',
        'offline': 'Offline',
        'type_message': 'Nachricht eingeben...',
        'send': 'Senden',
        'chat_info': 'Chat-Info',
        'media': 'Medien',
        'files': 'Dateien',
        'links': 'Links',
        'create_group': 'Gruppe erstellen',
        'add_members': 'Mitglieder hinzufügen',
        'group_name': 'Gruppenname',
        'create': 'Erstellen',
        'cancel': 'Abbrechen',
        'typing': 'tippt...',
        
        // Login/Register
        'welcome_back': 'Willkommen zurück',
        'login_subtitle': 'Melden Sie sich bei Ihrem Konto an, um weiterhin die besten Teamkollegen zu finden',
        'email': 'E-Mail',
        'password': 'Passwort',
        'remember_me': 'Angemeldet bleiben',
        'forgot_password': 'Passwort vergessen?',
        'no_account': 'Noch kein Konto?',
        'create_account': 'Konto erstellen',
        'join_community': 'Treten Sie der weltweit größten Community für internationale Studentenwettbewerbe bei',
        'full_name': 'Vollständiger Name',
        'confirm_password': 'Passwort bestätigen',
        'agree_terms': 'Ich stimme den Nutzungsbedingungen und der Datenschutzrichtlinie zu',
        'already_account': 'Haben Sie bereits ein Konto?',
        
        // Competitions page
        'competitions_title': 'Internationale Wettbewerbe erkunden',
        'competitions_subtitle': 'Entdecken Sie die neuesten globalen Wettbewerbsmöglichkeiten für Sie',
        'filter_by': 'Filtern nach',
        'all_categories': 'Alle Kategorien',
        'deadline': 'Frist',
        'team_size': 'Teamgröße',
        'difficulty': 'Schwierigkeit',
        'apply_filters': 'Filter anwenden',
        'reset_filters': 'Zurücksetzen',
        'competition_details': 'Wettbewerbsdetails',
        'organizer': 'Organisator',
        'category': 'Kategorie',
        'prize': 'Preis',
        'requirements': 'Anforderungen',
        'description': 'Beschreibung',
        'register_now': 'Jetzt anmelden',
        'find_teammates': 'Teamkollegen finden',
        
        // Find Teammates page
        'find_teammates_title': 'Teamkollegen finden',
        'find_teammates_subtitle': 'Durchsuchen Sie potenzielle Teamkollegen und knüpfen Sie Kontakte',
        'filter_teammates': 'Teamkollegen filtern',
        'skills': 'Fähigkeiten',
        'experience': 'Erfahrung',
        'location': 'Standort',
        'availability': 'Verfügbarkeit',
        'search_teammates': 'Teamkollegen suchen',
        'connect': 'Verbinden',
        'message': 'Nachricht',
        'view_profile': 'Profil anzeigen',
        
        // Profile page
        'my_profile': 'Mein Profil',
        'edit_profile': 'Profil bearbeiten',
        'basic_info': 'Grundinformationen',
        'university': 'Universität',
        'major': 'Hauptfach',
        'bio': 'Biografie',
        'my_skills': 'Meine Fähigkeiten',
        'add_skill': 'Fähigkeit hinzufügen',
        'my_competitions': 'Meine Wettbewerbe',
        'past_competitions': 'Vergangene Wettbewerbe',
        'achievements': 'Erfolge',
        'add_achievement': 'Erfolg hinzufügen',
        'save_changes': 'Änderungen speichern',
        'discard_changes': 'Änderungen verwerfen'
    },
    
    // 法语翻译
    'fr': {
        // Navigation
        'nav_home': 'Accueil',
        'nav_competitions': 'Compétitions',
        'nav_teammates': 'Trouver des Coéquipiers',
        'nav_profile': 'Profil',
        'login': 'Connexion',
        'register': 'Inscription',
        
        // Notifications
        'notifications': 'Notifications',
        'mark_all_read': 'Marquer tout comme lu',
        'no_notifications': 'Pas de nouvelles notifications',
        'see_all_notifications': 'Voir toutes les notifications',
        
        // Home page
        'hero_title': 'Trouvez vos Coéquipiers Parfaits pour les Compétitions Internationales',
        'hero_subtitle': 'Connectez-vous avec des étudiants du monde entier, constituez l\'équipe parfaite et remportez des compétitions internationales',
        'get_started': 'Commencer',
        'learn_more': 'En savoir plus',
        'features_title': 'Pourquoi Choisir teamify?',
        'feature1_title': 'Vivier de Talents Mondial',
        'feature1_desc': 'Accédez à des étudiants exceptionnels du monde entier pour trouver votre partenaire idéal',
        'feature2_title': 'Correspondance de Compétences',
        'feature2_desc': 'Système de mise en relation intelligent basé sur les compétences, l\'expérience et les intérêts',
        'feature3_title': 'Ressources de Compétition',
        'feature3_desc': 'Obtenez les dernières informations sur les compétitions, les délais et les exigences',
        'popular_competitions': 'Compétitions Populaires',
        'view_all': 'Voir tout',
        'days_left': 'jours restants',
        'testimonials_title': 'Ce que disent nos utilisateurs',
        'cta_title': 'Prêt à commencer votre parcours de compétition?',
        'cta_subtitle': 'Inscrivez-vous aujourd\'hui et trouvez vos coéquipiers idéaux',
        'cta_button': 'S\'inscrire maintenant',
        
        // Footer
        'quick_links': 'Liens rapides',
        'about_us': 'À propos de nous',
        'contact_us': 'Contactez-nous',
        'privacy_policy': 'Politique de confidentialité',
        'terms_of_service': 'Conditions d\'utilisation',
        'follow_us': 'Suivez-nous',
        'copyright': 'Tous droits réservés',
        
        // Chat
        'chats': 'Discussions',
        'contacts': 'Contacts',
        'search': 'Rechercher',
        'new_chat': 'Nouvelle discussion',
        'online': 'En ligne',
        'offline': 'Hors ligne',
        'type_message': 'Tapez un message...',
        'send': 'Envoyer',
        'chat_info': 'Infos de discussion',
        'media': 'Médias',
        'files': 'Fichiers',
        'links': 'Liens',
        'create_group': 'Créer un groupe',
        'add_members': 'Ajouter des membres',
        'group_name': 'Nom du groupe',
        'create': 'Créer',
        'cancel': 'Annuler',
        'typing': 'en train d\'écrire...',
        
        // Login/Register
        'welcome_back': 'Bienvenue',
        'login_subtitle': 'Connectez-vous à votre compte pour continuer à trouver les meilleurs coéquipiers',
        'email': 'Email',
        'password': 'Mot de passe',
        'remember_me': 'Se souvenir de moi',
        'forgot_password': 'Mot de passe oublié?',
        'no_account': 'Vous n\'avez pas de compte?',
        'create_account': 'Créer un compte',
        'join_community': 'Rejoignez la plus grande communauté mondiale de compétitions étudiantes internationales',
        'full_name': 'Nom complet',
        'confirm_password': 'Confirmer le mot de passe',
        'agree_terms': 'J\'accepte les conditions d\'utilisation et la politique de confidentialité',
        'already_account': 'Vous avez déjà un compte?',
        
        // Competitions page
        'competitions_title': 'Explorer les Compétitions Internationales',
        'competitions_subtitle': 'Découvrez les dernières opportunités de compétition mondiale pour vous',
        'filter_by': 'Filtrer par',
        'all_categories': 'Toutes les catégories',
        'deadline': 'Date limite',
        'team_size': 'Taille de l\'équipe',
        'difficulty': 'Difficulté',
        'apply_filters': 'Appliquer les filtres',
        'reset_filters': 'Réinitialiser',
        'competition_details': 'Détails de la compétition',
        'organizer': 'Organisateur',
        'category': 'Catégorie',
        'prize': 'Prix',
        'requirements': 'Exigences',
        'description': 'Description',
        'register_now': 'S\'inscrire maintenant',
        'find_teammates': 'Trouver des coéquipiers',
        
        // Find Teammates page
        'find_teammates_title': 'Trouver des Coéquipiers',
        'find_teammates_subtitle': 'Parcourez les coéquipiers potentiels et établissez des connexions',
        'filter_teammates': 'Filtrer les coéquipiers',
        'skills': 'Compétences',
        'experience': 'Expérience',
        'location': 'Emplacement',
        'availability': 'Disponibilité',
        'search_teammates': 'Rechercher des coéquipiers',
        'connect': 'Se connecter',
        'message': 'Message',
        'view_profile': 'Voir le profil',
        
        // Profile page
        'my_profile': 'Mon profil',
        'edit_profile': 'Modifier le profil',
        'basic_info': 'Informations de base',
        'university': 'Université',
        'major': 'Spécialité',
        'bio': 'Biographie',
        'my_skills': 'Mes compétences',
        'add_skill': 'Ajouter une compétence',
        'my_competitions': 'Mes compétitions',
        'past_competitions': 'Compétitions passées',
        'achievements': 'Réalisations',
        'add_achievement': 'Ajouter une réalisation',
        'save_changes': 'Enregistrer les modifications',
        'discard_changes': 'Annuler les modifications'
    }
};